import {readFile,writeFile,mkdir,copyFile,cp,rm} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {cudaAST} from '../src/webgpu/clang.mjs';
import {lower} from '../src/webgpu/lower.mjs';
const cuda=await readFile('generated/clearwater.cu','utf8');
const webshaderRevision='ef46ff1bf02a306bad94ddc18286d25d3d902c14';
if(execFileSync('git',['rev-parse','HEAD'],{cwd:'vendor/webshader',encoding:'utf8'}).trim()!==webshaderRevision)throw Error('Unexpected CUDA WebShader revision');
execFileSync('git',['diff','--exit-code','HEAD','--','src'],{cwd:'vendor/webshader',stdio:'inherit'});
const ast=await cudaAST(cuda);
const functions=ast.inner.filter(n=>n.kind==='FunctionDecl'&&n.inner?.some(x=>x.kind==='CompoundStmt'));
const kinds=new Map();function walk(n){kinds.set(n.kind,(kinds.get(n.kind)||0)+1);for(const c of n.inner||[])walk(c);}
functions.forEach(walk);
console.log(`Parsed ${functions.length} CUDA functions with Clang.`);
const result=lower(ast);
await writeFile('generated/bend-evaluator.wgsl',result.source);
await writeFile('generated/bend-lowering.json',JSON.stringify(result.functions,null,2));
const runtime=await readFile('src/webgpu/runtime.wgsl','utf8');
const meta={...result.metadata,ENTRY:result.metadata.FID_RENDER_SCENE,PRIVATE_WORDS:2048};
const header=Object.entries(meta).map(([key,value])=>`const CW_${key}:u32=${value}u;`).join('\n');
await writeFile('generated/clearwater.wgsl',header+'\n'+runtime+'\n'+result.source);
await writeFile('generated/webgpu-metadata.json',JSON.stringify(meta,null,2));
const hashes={};for(const path of ['src/clearwater.bend','generated/clearwater.cu','generated/clearwater.wgsl'])hashes[path]=createHash('sha256').update(await readFile(path)).digest('hex');
await writeFile('generated/webgpu-manifest.json',JSON.stringify({bend:'3378e6237ed431d17629efd36d24c96241815b7e',webshader:webshaderRevision,hashes,backend:'direct-wgsl',floatPrecision:32},null,2)+'\n');
await mkdir('dist/generated',{recursive:true});
await rm('dist/generated/clearwater-program.bin',{force:true});
for(const file of ['webgpu.html','webgpu-app.js','webgpu.js','generated/clearwater.wgsl','generated/webgpu-metadata.json','generated/webgpu-manifest.json'])await copyFile(file,'dist/'+file);
await mkdir('dist/vendor/webshader',{recursive:true});await cp('vendor/webshader/src','dist/vendor/webshader/src',{recursive:true});
await copyFile('vendor/webshader/LICENSE','licenses/CUDA-WebShader-MIT.txt');await copyFile('licenses/CUDA-WebShader-MIT.txt','dist/licenses/CUDA-WebShader-MIT.txt');
console.log(`Lowered ${result.functions.length} device functions to WGSL.`);
